### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by jlu5** [Sazpaimon/pylink-discord#1]
Before I work on this further (and eventually import into contrib, most likely) - I just want to confirm that I can use this module under the terms of GPLv2[1].

[1] I say GPLv2 specifically because discord_formtter.py seems to originate from https://github.com/Hackndo/discord-irc-sync, which is licensed as such. (GPL requires derivative works to be of the same license).

**Comment by Sazpaimon** [comment]
Whoops, I missed this, sorry.
Regarding discord-irc-sync, I only threw that in there as a quick and dirty solution, and am replacing it with something not as discord-specific and more compliant with various markdown eccentricities. Once that's in place, I assume I can slap an MIT license on it to make it safe to upstream.

**Comment by jlu5** [comment]
I started some continued work and testing on this @ https://github.com/PyLink/pylink-discord

Leaving the formatter as is, can I refer to your part of the code under the GPL too?
